require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - app/channels/**/*
    - app/mailers/**/*
    - app/jobs/**/*
    - app/models/**
    - node_modules/**/**
    - Gemfile
    - Rakefile
    - config.ru
    - app/controllers/application_controller.rb
    - app/helpers/application_helper.rb
    - spec/spec_helper.rb
    # rails tutorialのコードを参考にしているため
    - spec/rails_helper.rb
    - app/helpers/sessions_helper.rb
    # docker化後追記
    - 'vendor/**/*'

# 新しいオプション(20200323)
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
# ここまで

#コメントにASCII文字を使って良い
Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: 100

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

#it ''　内で日本語の使用を許可する
RSpec/ContextWording:
  Enabled: false

#let!の使用を許可する
RSpec/LetSetup:
  Enabled: false

#テストに複数行で記載してもよい
RSpec/MultipleExpectations:
  Enabled: false

#テストの行が5行以上になっても良い
RSpec/ExampleLength:
  Enabled: false

#空のテストがあっても良い
RSpec/EmptyExampleGroup:
  Enabled: false
