require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - app/channels/**/*
    - app/mailers/**/*
    - app/jobs/**/*
    - app/models/**
    - node_modules/**/**
    - Gemfile
    - Rakefile
    - config.ru
    - app/controllers/application_controller.rb
    - app/helpers/application_helper.rb
    - spec/spec_helper.rb
    # rails tutorialのコードを参考にしているため
    - spec/rails_helper.rb
    - app/helpers/sessions_helper.rb

Rails:
  Enabled: true

# 新しいオプション(20200323)
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
# ここまで

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: 100

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

#テストの行が5行以上になっても良い
Metrics/ExampleLength:
  Enabled: false

#空のテストがあっても良い
Metrics/EmptyExampleGroup:
  Enabled: false

Metrics/MultipleExpectations:
  Enabled: false

#コメントにASCII文字を使って良い
AsciiComments:
  Enabled: false
